from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


def create_report_pdf(report_text, filename="medical_analysis.pdf"):
    """
    Generate a PDF containing the AI medical report analysis.
    """

    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("<b>AI Medical Report Analysis</b>", styles["Title"])
    )

    story.append(
        Paragraph("<br/>", styles["BodyText"])
    )

    for line in report_text.split("\n"):

        if line.strip():

            story.append(
                Paragraph(line, styles["BodyText"])
            )

    story.append(
        Paragraph("<br/><br/>", styles["BodyText"])
    )

    story.append(
        Paragraph(
            "<b>Disclaimer:</b> This report is generated by AI for educational purposes only. It is not a medical diagnosis. Please consult a qualified healthcare professional.",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename